# Numpy

In [2]:
import numpy as np # importe la librairies et l'associe au raccourci 'np'

## créer un tableau

In [4]:
# à partir d'une liste ou d'un tuple
a = [1,2,5,6,-8,1]
arr = np.array(a)
print a

[1, 2, 5, 6, -8, 1]


In [3]:
# à partir d'un générateur
print np.arange(5)
print np.arange(1,10)
print np.arange(1,20,2)
print np.linspace(0,1,10)
print np.zeros(5) # size 5, filled with zeroes
print np.ones(5) # size 5, filled with ones

[0 1 2 3 4]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  3  5  7  9 11 13 15 17 19]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## opérations sur les tableaux

In [4]:
a = np.arange(10)
print a - 5
print a * 2
print a * 2 - 5
print np.exp(a)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  2  4  6  8 10 12 14 16 18]
[-5 -3 -1  1  3  5  7  9 11 13]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [13]:
a = np.arange(10)
b = np.arange(10)
print a * b
print a.dot(b)

[ 0  1  4  9 16 25 36 49 64 81]
285


## indexing

In [20]:
print np.arange(25)[0:12] # slicing
print np.arange(10)[::-1] # revert array
print np.arange(10) > 5 # a comparison operation returns an array of bool ...
print (np.arange(10) > 5) * (np.arange(10) < 8) # ... which are very easy to manipulate
# return a list of indexes which can be passed 
# to an array of same shape - but not the same array
a = np.arange(10)
indexes = np.nonzero((a > 5) * (a < 8))
print a[indexes]

a = np.exp(np.arange(10, dtype=float) / 10.)
print a
print a[indexes]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[9 8 7 6 5 4 3 2 1 0]
[False False False False False False  True  True  True  True]
[False False False False False False  True  True False False]
[6 7]
[1.         1.10517092 1.22140276 1.34985881 1.4918247  1.64872127
 1.8221188  2.01375271 2.22554093 2.45960311]
[1.8221188  2.01375271]


## toujours penser en terme d'opérations matricielles, toujours réflechir avant de faire une boucle for

In [27]:
a = np.arange(100).reshape(10,10)
print a
b = np.arange(100).reshape(10,10)
c = a * b
print c
% timeit a * b

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[   0    1    4    9   16   25   36   49   64   81]
 [ 100  121  144  169  196  225  256  289  324  361]
 [ 400  441  484  529  576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209 2304 2401]
 [2500 2601 2704 2809 2916 3025 3136 3249 3364 3481]
 [3600 3721 3844 3969 4096 4225 4356 4489 4624 4761]
 [4900 5041 5184 5329 5476 5625 5776 5929 6084 6241]
 [6400 6561 6724 6889 7056 7225 7396 7569 7744 7921]
 [8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]]
The slowest run took 38.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best

In [26]:
a = np.arange(100).reshape(10,10)
b = np.arange(100).reshape(10,10)
def product(_a, _b):
    c = np.empty_like(a)
    c.fill(np.nan)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            c[i,j] = a[i,j] * b[i,j]
    return c
print product(a, b)
% timeit product(a, b)
        

[[   0    1    4    9   16   25   36   49   64   81]
 [ 100  121  144  169  196  225  256  289  324  361]
 [ 400  441  484  529  576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209 2304 2401]
 [2500 2601 2704 2809 2916 3025 3136 3249 3364 3481]
 [3600 3721 3844 3969 4096 4225 4356 4489 4624 4761]
 [4900 5041 5184 5329 5476 5625 5776 5929 6084 6241]
 [6400 6561 6724 6889 7056 7225 7396 7569 7744 7921]
 [8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]]
10000 loops, best of 3: 35.4 µs per loop


## statistique de base sur des tableaux

In [40]:
a = np.random.standard_normal(100000)
a[0] = np.nan
print a
print np.nanmean(a)
print np.nanmedian(a)
print np.nanpercentile(a, 10)
print np.nanpercentile(a, 90)
print np.nanmin(a)
print np.nanmax(a)
print np.nonzero(np.isnan(a))

[        nan  0.85058773  2.10506325 ...  0.2546696  -0.21939749
  0.34794939]
0.0011455239406846782
0.0007221459948510592
-1.2804301907142988
1.2867596112687691
-4.258480910929663
4.557603873795864
(array([0]),)


In [41]:
vit[np.nonzero(vit_err > 5)] = np.nan



NameError: name 'vit' is not defined

In [ ]:
print np.min